### ISSUE TITLE
Cannot get rid of this!

### ISSUE THREAD

**Issue by eeezzz2** [SrWither/VsVim#1]
This config never worked for me, I tried to get it working but it was just so messy. So I uninstalled it, completely removed (rm -rf) all files associated with it, uninstalled and re-installed neovim and I was still getting issues with neovim, though I was able to find some configurations to delete so at least neovim is now running properly. The ISSUE: is that every single time I open a terminal, I see this message: "VsVim '1.6.2' available, Update with 'vsvupg'. I believe it is also causing my terminal to stall when opening, wasting time.

Super super aggravating. I've re-installed my entire operating system just to get rid of this, and it still hasn't got rid of it. What's the deal? Please help me get this off of my computer, or I'll be forced to have to redo my entire system from scratch. All for a repository that never worked to begin with. 

Smells like malware.

![Screenshot from 2022-03-04 20-30-16](https://user-images.githubusercontent.com/98776302/160507323-55333c7c-77e0-4945-86ab-439b5fd40b9e.png)

**Comment by SrWither** [comment]
wow I didn't think that could happen, so I removed those lines in the installer.
sorry for the inconvenience
